version: "3.8"

services:
  postgresql:
    platform: linux/x86_64
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESQL_USER
      - POSTGRES_PASSWORD=$POSTGRESQL_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESQL_DATABASE
    ports:
      - $POSTGRESQL_LOCAL_PORT:$POSTGRESQL_DOCKER_PORT
  app:
    depends_on:
      - postgresql
    restart: on-failure
    image: apavliuk/currency-rate-service
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.r2dbc.url"  : "r2dbc:postgresql://postgresql:$POSTGRESQL_DOCKER_PORT/$POSTGRESQL_DATABASE?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC",
        "spring.r2dbc.username" : "$POSTGRESQL_USER",
        "spring.r2dbc.password" : "$POSTGRESQL_ROOT_PASSWORD",
        "spring.liquibase.url"  : "jdbc:postgresql://postgresql:$POSTGRESQL_DOCKER_PORT/$POSTGRESQL_DATABASE?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC",
        "spring.liquibase.user" : "$POSTGRESQL_USER",
        "spring.liquibase.password" : "$POSTGRESQL_ROOT_PASSWORD",
        "currencies-service.url" : "$CURRENCIES_SERVICE_URL"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"